FROM node:24-bookworm-slim@sha256:6f7b03f7c2c8e2e784dcf9295400527b9b1270fd37b7e9a7285cf83b6951452d AS deps

WORKDIR /app

COPY package.json package-lock.json ./
COPY apps/api/package.json apps/api/package.json

RUN npm ci

FROM deps AS build

COPY . .

RUN npm run build --workspace=apps/api
RUN npm prune --omit=dev --workspaces

# Remove npm's internal lock metadata before copying to runtime.
# This file is generated by npm ci and contains the full transitive
# devDependency tree. Trivy scans it as a manifest and would report
# CVEs for packages that were already removed by npm prune.
RUN rm -f node_modules/.package-lock.json

FROM node:24-bookworm-slim@sha256:6f7b03f7c2c8e2e784dcf9295400527b9b1270fd37b7e9a7285cf83b6951452d AS runtime

# Fix OS-level CVEs in final image — unqualified upgrade catches all
# available Debian security patches without needing to hand-list packages.
RUN apt-get update && apt-get upgrade -y && rm -rf /var/lib/apt/lists/*

# npm 11.x bundled with Node 24 (11.16.0) is recent enough that the
# cross-spawn/minimatch CVEs that forced an upgrade from Node 20's npm
# 10.8.2 are already resolved. Keep the upgrade line defensive in case
# a newer patch fixes additional bundle CVEs that Trivy flags.
RUN npm install -g npm@11 && rm -rf /root/.npm

ENV NODE_ENV=production
ENV PORT=3001
ENV UPLOAD_TMP_DIR=/var/lib/floe/upload

WORKDIR /app

# package-lock.json omitted intentionally: it contains the full transitive
# devDependency tree that Trivy scans as a manifest, producing 12 false-
# positive HIGH findings for packages that were already pruned by
# `npm prune --omit=dev --workspaces` in the build stage. The lock file
# is only needed for `npm ci` reproducibility, never at runtime under
# `node apps/api/dist/server.js`.
COPY --from=build /app/package.json ./
COPY --from=build /app/node_modules /app/node_modules
COPY --from=build /app/apps/api/package.json /app/apps/api/package.json
COPY --from=build /app/apps/api/node_modules /app/apps/api/node_modules
COPY --from=build /app/apps/api/dist /app/apps/api/dist

RUN mkdir -p /var/lib/floe/upload && chown -R node:node /var/lib/floe /app

USER node

EXPOSE 3001

HEALTHCHECK --interval=30s --timeout=5s --start-period=20s --retries=3 \
  CMD node -e "fetch(`http://127.0.0.1:${process.env.PORT || 3001}/health`).then((res) => process.exit(res.ok ? 0 : 1)).catch(() => process.exit(1))"

CMD ["node", "apps/api/dist/server.js"]
