FROM node:20-bookworm-slim@sha256:2cf067cfed83d5ea958367df9f966191a942351a2df77d6f0193e162b5febfc0 AS deps

WORKDIR /app

COPY package.json package-lock.json ./
COPY apps/api/package.json apps/api/package.json

RUN npm ci

FROM deps AS build

COPY . .

RUN npm run build --workspace=apps/api
RUN npm prune --omit=dev --workspaces

# Remove npm's internal lock metadata before copying to runtime.
# This file is generated by npm ci and contains the full transitive
# devDependency tree. Trivy scans it as a manifest and would report
# CVEs for packages that were already removed by npm prune.
RUN rm -f node_modules/.package-lock.json

FROM node:20-bookworm-slim@sha256:2cf067cfed83d5ea958367df9f966191a942351a2df77d6f0193e162b5febfc0 AS runtime

# Fix OS-level CVEs in final image — unqualified upgrade catches all
# available Debian security patches without needing to hand-list packages.
RUN apt-get update && apt-get upgrade -y && rm -rf /var/lib/apt/lists/*

# Upgrade npm so its bundled transitive dependencies (cross-spawn, glob,
# minimatch, sigstore, tar) no longer trigger HIGH-severity Trivy findings.
# node:20-bookworm-slim ships npm 10.8.2, which bundles vulnerable versions
# of these packages in /usr/local/lib/node_modules/npm/node_modules/.
# npm 11 is the latest major that supports Node 20 (npm 12 requires Node 22+).
RUN npm install -g npm@11 && rm -rf /root/.npm

ENV NODE_ENV=production
ENV PORT=3001
ENV UPLOAD_TMP_DIR=/var/lib/floe/upload

WORKDIR /app

# package-lock.json omitted intentionally: it contains the full transitive
# devDependency tree that Trivy scans as a manifest, producing 12 false-
# positive HIGH findings for packages that were already pruned by
# `npm prune --omit=dev --workspaces` in the build stage. The lock file
# is only needed for `npm ci` reproducibility, never at runtime under
# `node apps/api/dist/server.js`.
COPY --from=build /app/package.json ./
COPY --from=build /app/node_modules /app/node_modules
COPY --from=build /app/apps/api/package.json /app/apps/api/package.json
COPY --from=build /app/apps/api/node_modules /app/apps/api/node_modules
COPY --from=build /app/apps/api/dist /app/apps/api/dist

RUN mkdir -p /var/lib/floe/upload && chown -R node:node /var/lib/floe /app

USER node

EXPOSE 3001

HEALTHCHECK --interval=30s --timeout=5s --start-period=20s --retries=3 \
  CMD node -e "fetch(`http://127.0.0.1:${process.env.PORT || 3001}/health`).then((res) => process.exit(res.ok ? 0 : 1)).catch(() => process.exit(1))"

CMD ["node", "apps/api/dist/server.js"]
